# Generated by Django 5.2.1 on 2025-12-26 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageappointment',
            name='attendant',
            field=models.ForeignKey(limit_choices_to={'user_type': 'attendant'}, on_delete=django.db.models.deletion.CASCADE, related_name='package_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
