# Generated by Django 5.2.1 on 2025-12-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_serviceimage_archived_alter_service_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historylog',
            name='type',
            field=models.CharField(choices=[('Service', 'Service'), ('Product', 'Product'), ('Package', 'Package'), ('Clinic Hours', 'Clinic Hours'), ('Closed Day', 'Closed Day')], max_length=12),
        ),
    ]
