# Generated by Django 5.2.1 on 2025-12-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Age of the user (automatically calculated from birthday)', null=True),
        ),
    ]
