# Generated by Django 5.2.1 on 2025-12-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_age'),
        ('appointments', '0020_alter_appointment_attendant'),
        ('packages', '0003_alter_packageappointment_attendant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendant',
        ),
    ]
