# Generated by Django 5.2.1 on 2026-01-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_delete_attendant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendantLeaveRequest',
        ),
    ]
