# Generated by Django 5.2.1 on 2025-12-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_alter_feedback_unique_together_reschedulerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pending', 'Pending'), ('rescheduled', 'Rescheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=15),
        ),
    ]
