# Generated by Django 5.2.1 on 2025-12-11 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity of product ordered (for product appointments only)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='template_type',
            field=models.CharField(choices=[('scheduled', 'Appointment Scheduled (Pending Confirmation)'), ('confirmation', 'Appointment Confirmation'), ('reminder', 'Appointment Reminder'), ('cancellation', 'Cancellation Notification'), ('package_confirmation', 'Package Confirmation'), ('attendant_reassignment', 'Attendant Reassignment'), ('attendant_assignment', 'Attendant Assignment'), ('custom', 'Custom Template')], max_length=30),
        ),
    ]
