# Generated by Django 5.2.1 on 2025-12-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0020_alter_appointment_attendant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationrequest',
            name='cancellation_notes',
            field=models.TextField(blank=True, help_text='Additional details from patient about cancellation', null=True),
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('changed_mind', 'Changed My Mind'), ('scheduling_conflict', 'Scheduling Conflict'), ('illness', 'Health/Illness Issue'), ('financial', 'Payment/Financial Issue'), ('service_quality', 'Previous Poor Experience'), ('found_alternative', 'Found Alternative Service'), ('other', 'Other Reason')], help_text='Categorized reason for cancellation (patient feedback)', max_length=50, null=True),
        ),
    ]
