# Generated by Django 5.2.1 on 2026-01-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0021_cancellationrequest_cancellation_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellationrequest',
            name='cancellation_notes',
        ),
        migrations.RemoveField(
            model_name='cancellationrequest',
            name='cancellation_reason',
        ),
    ]
