# Generated by Django 5.2.1 on 2026-01-05 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0022_remove_cancellation_feedback_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('one_day', 'One Day Before'), ('two_day', 'Two Days Before'), ('custom', 'Custom')], default='two_day', max_length=15)),
                ('sent', models.BooleanField(default=False, help_text='Whether the reminder SMS has been sent')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the SMS reminder was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_reminders', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'SMS Reminder',
                'verbose_name_plural': 'SMS Reminders',
                'db_table': 'sms_reminders',
                'ordering': ['-created_at'],
                'unique_together': {('appointment', 'reminder_type')},
            },
        ),
    ]
