# Generated by Django 5.2.1 on 2026-01-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0024_room_appointment_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendantunavailabilityrequest',
            name='pending_reassignment_choice',
            field=models.BooleanField(default=True, help_text='True if patient needs to make a selection, False after choice is made'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pending', 'Pending'), ('approved', 'Approved'), ('rescheduled', 'Rescheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=15),
        ),
    ]
