# Generated by Django 5.2.1 on 2026-01-12 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0028_add_diagnosis_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='equipment_rating',
            field=models.IntegerField(blank=True, help_text='Rating from 1 to 5 stars for equipment', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='feedback',
            name='room_rating',
            field=models.IntegerField(blank=True, help_text='Rating from 1 to 5 stars for room', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='smsreminder',
            name='reminder_type',
            field=models.CharField(choices=[('one_day', 'One Day Before'), ('two_day', 'Two Days Before'), ('one_hour', 'One Hour Before'), ('custom', 'Custom')], default='two_day', max_length=15),
        ),
    ]
