# Generated by Django 5.2.1 on 2026-01-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0028_add_diagnosis_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsreminder',
            name='reminder_type',
            field=models.CharField(choices=[('one_day', 'One Day Before'), ('two_day', 'Two Days Before'), ('one_hour', 'One Hour Before'), ('custom', 'Custom')], default='two_day', max_length=15),
        ),
    ]
