# Generated by Django 5.2.1 on 2026-02-09 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0029_add_one_hour_reminder_type'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE feedback ADD COLUMN IF NOT EXISTS equipment_rating integer;
            ALTER TABLE feedback ADD COLUMN IF NOT EXISTS room_rating integer;
            """,
            reverse_sql="""
            ALTER TABLE feedback DROP COLUMN IF EXISTS equipment_rating;
            ALTER TABLE feedback DROP COLUMN IF EXISTS room_rating;
            """,
            state_operations=[
                migrations.AddField(
                    model_name='feedback',
                    name='equipment_rating',
                    field=models.IntegerField(blank=True, help_text='Rating from 1 to 5 stars for equipment', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
                ),
                migrations.AddField(
                    model_name='feedback',
                    name='room_rating',
                    field=models.IntegerField(blank=True, help_text='Rating from 1 to 5 stars for room', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
                ),
            ]
        )
    ]
