# Generated by Django 5.2.1 on 2025-12-11 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productimage_archived_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Stock Added'), ('minus', 'Stock Reduced'), ('order', 'Customer Order'), ('return', 'Stock Returned'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for additions, negative for reductions')),
                ('previous_stock', models.IntegerField(help_text='Stock level before this change')),
                ('new_stock', models.IntegerField(help_text='Stock level after this change')),
                ('reason', models.TextField(blank=True, help_text='Reason for stock change', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='products.product')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock History',
                'verbose_name_plural': 'Stock History',
                'db_table': 'stock_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
